Fix valley index AttributeError
Fixed: 
AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'
pd.datetime object expected instead of a np 64 int.